# Base configs
baseurl: "https://thabanglukhetho.github.io/Photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Thabanglukhetho"
subtitle: "One step at a time."
author: "Thabanglukhetho"
header:
 title: "Photography"
 subtitle: "by Thabanglukhetho"
footer:
 name: "Hey there, my name is Thabang"
 bio: "Welcome to the master photography ThabangLukhetho's gallery. I'm based in South Africa from a BIG and famous township called Soshanguve, I'm a self-taught visual artist and enjoy capturing moments either using my Nikon DSLR or my Google Pixel mobile phone. It started with a 2 megapixel Nokia phone in 2017 and from there it has been nothing but a journey of discovery and adventure. My interest ranges from documentary, street, abstract to nature photography. For high-quality printouts please DM on my socials or send me an email."
web_design: "TL"
social_urls:
  facebook: "https://www.facebook.com/thabanglukhetho"
  twitter: "https://twitter.com/thabangline"
  instagram: "https://www.instagram.com/thabanglukhetho"
  youtube: "https://www.youtube.com/channel/UCn7LVtcyxdo0UYThRQmM5jQ"
