# Base configs
baseurl: "https://thabanglukhetho.github.io/Photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Thabanglukhetho"
subtitle: "One step at a time."
author: "Thabanglukhetho"
header:
 title: "Photography"
 subtitle: "by Thabanglukhetho"
footer:
 name: "Hey there, my name is Thabang"
 bio: "Welcome to the master photography ThabangLukhetho's gallery. I'm based in South Africa from a BIG and famous township called Soshanguve, I'm a self-taught photographer and enjoy capturing moments either using my Nikon DSLR or my Google Pixel mobile phone. I believe the world is both beautiful and ugly, but the moments that passes through space and time are priceless and deserve to be captured. Send me an email or DM me on my social for high-quality printouts, we provide free shipment across the globe. To see the world through my mind please follow me as I embark on a journey of discovery."
web_design: "TL"
social_urls:
  facebook: "https://www.facebook.com/thabanglukhetho"
  twitter: "https://twitter.com/thabangline"
  instagram: "https://www.instagram.com/thabanglukhetho"
  youtube: "https://www.youtube.com/channel/UCn7LVtcyxdo0UYThRQmM5jQ"
