# Base configs
baseurl: "https://thabanglukhetho.github.io/Photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Thabanglukhetho"
subtitle: "Go nkga tayera!"
author: "Thabanglukhetho"
header:
 title: "Photography"
 subtitle: "by Thabanglukhetho"
footer:
 name: "Hey there, my name is Thabang"
 bio: "I am a student of the multiverse from South Africa. I love capturing random moments in space and time, follow my journey of storytelling."
web_design: "TL"
social_urls:
  facebook: "https://www.facebook.com/thabanglukhetho"
  twitter: "https://twitter.com/thabangline"
  instagram: "https://www.instagram.com/thabanglukhetho"
