# Base configs
baseurl: "https://thabanglukhetho.github.io/Photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Thabanglukhetho"
subtitle: "One step at a time."
author: "Thabanglukhetho"
header:
 title: "Photography"
 subtitle: "by Thabanglukhetho"
footer:
 name: "Hey there, my name is Thabang"
 bio: "Welcome to the master photography ThabangLukhetho's gallery. I'm a self-taught visual artist based in South Africa from the a diverse township called Soshanguve. I enjoy  capturing all the experiences life into artistic memories. I have been taking photos ever since my first phone in 2013, but I only started showcasing some of my work on social media from 2017, since then it has been a journey of discovery and adventure filled with moments frozen in time. My interest span from nature, street, documentary
 , abstract and sometimes potrait photography. For high-quality display prints enquiries, feel free to DM me on my socials or email me at thabangvision@gmail.com. We also provide safe and reliable shipment world-wide."
web_design: "TL"
social_urls:
  facebook: "https://www.facebook.com/thabanglukhetho"
  twitter: "https://twitter.com/thabangline"
  instagram: "https://www.instagram.com/thabanglukhetho"
  # youtube: "https://www.youtube.com/channel/UCn7LVtcyxdo0UYThRQmM5jQ"
