# Base configs
baseurl: "https://thabanglukhetho.github.io/Photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Thabanglukhetho"
subtitle: "Go nkga tayera!"
author: "Thabanglukhetho"
header:
 title: "Photography"
 subtitle: "by Thabanglukhetho"
footer:
 name: "Hey there, my name is Thabang"
 bio: "Welcome to the master photography ThabangLukhetho gallery. I'm from South Africa, and enjoy capturing moments, I use whatever I have on me from a mobile phone to a DSRL."
web_design: "TL"
social_urls:
  facebook: "https://www.facebook.com/thabanglukhetho"
  twitter: "https://twitter.com/thabangline"
  instagram: "https://www.instagram.com/thabanglukhetho"
  youtube: "https://www.youtube.com/channel/UCn7LVtcyxdo0UYThRQmM5jQ"
